name: fridge_recipe
description: A new Flutter project.
version: 1.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.1
  intl: ^0.19.0
  http: ^1.1.0
  image_picker: ^1.0.4
  fl_chart: ^0.66.0
  camera: ^0.11.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_confetti: ^0.1.0
  lottie: ^3.0.0
  uuid: ^4.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
